template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "trav1236"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-rmg"
__UND2C__ = "rmg"
__UNDEFINED__ = "Traveller Norwegian"
__UND__ = "rmg"
