template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "trav1236"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-rmg"
__UND2C__ = "rmg"
__UNDEFINED__ = "Traveller Norwegian"
__UND__ = "rmg"
